name: Node.js CI

on:
  pull_request:
    branches: ["main"]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm ci

      - name: Save node_modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules
      - run: npm run build --if-present

  docker:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Add environments
        run: |
          echo VITE_BACK_API=${{secrets.BACK_URL}} > .env
          echo VITE_SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/origami-flow-ui:latest
